-module(euler045).
-export([go/0]).

%% Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
%% Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
%% Pentagonal 	  	Pn=n(3n|1)/2 	  	1, 5, 12, 22, 35, ...
%% Hexagonal 	  	Hn=n(2n|1) 	  	1, 6, 15, 28, 45, ...

%% It can be verified that T285 = P165 = H143 = 40755.

%% Find the next triangle number that is also pentagonal and hexagonal.
%% Answer is: 1533776805

go() ->
    Triangles = sets:from_list([triangle(X)|| X <- lists:seq(1,100000)]),
    Pentagonals = sets:from_list([pentagonal(X)|| X <- lists:seq(1,100000)]),
    Hexagonals = sets:from_list([hexagonal(X) || X <- lists:seq(1,100000)]),
    AllThree = sets:intersection([Triangles, Pentagonals, Hexagonals]),
    sets:to_list(AllThree).

triangle(N) ->
    (N * (N + 1)) div  2.

pentagonal(N) ->
    (N * (3 * N - 1)) div 2.

hexagonal(N) ->
    N * (2 * N - 1).
