-module(euler044).
-export([go/1]).


%% Pentagonal numbers are generated by the formula, Pn=n(3n|1)/2. The first ten pentagonal numbers are:
%%
%% 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
%%
%% It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 | 22 = 48, is not pentagonal.
%%
%% Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and 
%% D = |Pk | Pj| is minimised; what is the value of D?

%% Answer is:
%% euler044:go(5000).
%% [5482660] 
%% Looks like N=2395 is where the magic happens

go(N) ->
    Pentagonals = [pentagonal(X)|| X <- lists:seq(1,N)],
    PentSet = sets:from_list(Pentagonals),
    test(Pentagonals, Pentagonals, PentSet, []).

test([X | Tail], Y, PentSet, Accum) ->
    case (sets:is_element(X - hd(Y), PentSet) and sets:is_element(X + hd(Y), PentSet)) of
	true -> test(Tail, Y, PentSet, Accum ++ [X - hd(Y)]); 
	false -> test(Tail, Y, PentSet, Accum)
    end;
test([], [_ | Tail], PentSet, Accum) ->
    test(Tail, Tail, PentSet, Accum);
test(_, [], _, Accum) -> Accum.


	    
pentagonal(N) ->
    (N * (3 * N - 1)) div 2.

